"""
email_service.py
================
Automated email notification service with anti-spam deduplication logic.
Sends HTML and plain text security alerts when Risk is HIGH or CRITICAL.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta
from typing import Dict, Tuple
from app.config import (
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USER,
    SMTP_PASS,
    ADMIN_EMAIL,
    EMAIL_ENABLED,
    HOSTNAME,
    ALERT_DEDUPLICATION_WINDOW_MINUTES
)
from app.utils import get_recommendation
from app.logger import logger

class EmailService:
    """Manages security alert email generation, SMTP transport, and spam suppression."""

    def __init__(self):
        self.enabled = EMAIL_ENABLED
        # Deduplication cache: key = (prediction, source_log), value = last_sent_datetime
        self._dedup_cache: Dict[Tuple[str, str], datetime] = {}
        self.dedup_window = timedelta(minutes=ALERT_DEDUPLICATION_WINDOW_MINUTES)

    def _should_suppress(self, prediction: str, source_log: str) -> bool:
        """Check if an alert for the same attack type and log source was sent recently."""
        key = (prediction, source_log)
        now = datetime.now()
        if key in self._dedup_cache:
            last_sent = self._dedup_cache[key]
            if now - last_sent < self.dedup_window:
                logger.info(
                    f"Email alert suppressed (anti-spam dedup window active for {prediction} on {source_log})"
                )
                return True

        self._dedup_cache[key] = now
        return False

    def send_alert(
        self,
        hostname: str,
        timestamp: str,
        prediction: str,
        confidence: float,
        risk: str,
        source_log: str,
        raw_log: str
    ) -> bool:
        """Send automated email alert for HIGH or CRITICAL security incidents."""
        if not self.enabled:
            logger.debug("Email alert skipped: Email service is disabled or unconfigured.")
            return False

        # Only send for HIGH or CRITICAL risks
        if risk not in ("HIGH", "CRITICAL"):
            return False

        # Anti-Spam check
        if self._should_suppress(prediction, source_log):
            return False

        recommendation = get_recommendation(prediction)
        subject = f"🚨 [{risk} ALERT] VPS Security Threat Detected: {prediction} on {hostname}"

        # Plain Text Body
        text_body = f"""
======================================================================
🛡️ ENTERPRISE VPS SECURITY AI — INCIDENT ALERT
======================================================================

Hostname     : {hostname}
Timestamp    : {timestamp}
Attack Type  : {prediction}
Confidence   : {confidence * 100:.2f}%
Risk Level   : {risk}
Source Log   : {source_log}

Raw Log Line:
{raw_log}

Recommended Action:
{recommendation}

======================================================================
Automated alert generated by Enterprise VPS Security Agent.
"""

        # HTML Body
        html_body = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; background-color: #f4f6f9; color: #333; margin: 0; padding: 20px; }}
        .card {{ background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); max-width: 650px; margin: 0 auto; overflow: hidden; }}
        .header-critical {{ background-color: #dc3545; color: #ffffff; padding: 20px; text-align: center; }}
        .header-high {{ background-color: #fd7e14; color: #ffffff; padding: 20px; text-align: center; }}
        .content {{ padding: 25px; }}
        .field {{ margin-bottom: 12px; font-size: 14px; }}
        .label {{ font-weight: bold; color: #495057; display: inline-block; width: 140px; }}
        .value {{ color: #212529; }}
        .badge {{ padding: 4px 8px; border-radius: 4px; font-weight: bold; color: #fff; }}
        .badge-critical {{ background-color: #dc3545; }}
        .badge-high {{ background-color: #fd7e14; }}
        .raw-box {{ background-color: #212529; color: #00ff66; font-family: monospace; padding: 12px; border-radius: 6px; white-space: pre-wrap; word-break: break-all; margin-top: 15px; }}
        .recom-box {{ background-color: #e7f5ff; border-left: 4px solid #1c7ed6; padding: 12px; margin-top: 15px; border-radius: 4px; }}
        .footer {{ background-color: #f8f9fa; text-align: center; padding: 12px; font-size: 12px; color: #6c757d; border-top: 1fr solid #dee2e6; }}
    </style>
</head>
<body>
    <div class="card">
        <div class="{ 'header-critical' if risk == 'CRITICAL' else 'header-high' }">
            <h2 style="margin:0;">🚨 Security Alert: {prediction}</h2>
            <p style="margin:5px 0 0 0;">Server: {hostname}</p>
        </div>
        <div class="content">
            <div class="field"><span class="label">Server Hostname:</span> <span class="value">{hostname}</span></div>
            <div class="field"><span class="label">Timestamp:</span> <span class="value">{timestamp}</span></div>
            <div class="field"><span class="label">Attack Type:</span> <span class="value"><strong>{prediction}</strong></span></div>
            <div class="field"><span class="label">AI Confidence:</span> <span class="value">{confidence * 100:.2f}%</span></div>
            <div class="field"><span class="label">Risk Severity:</span> <span class="badge { 'badge-critical' if risk == 'CRITICAL' else 'badge-high' }">{risk}</span></div>
            <div class="field"><span class="label">Log Source:</span> <span class="value"><code>{source_log}</code></span></div>

            <div style="margin-top:20px; font-weight:bold;">Intercepted Raw Log:</div>
            <div class="raw-box">{raw_log}</div>

            <div class="recom-box">
                <strong>📋 Actionable Recommendation:</strong><br>
                {recommendation}
            </div>
        </div>
        <div class="footer">
            Enterprise VPS Security AI Agent &bull; Autonomous Real-Time Monitoring
        </div>
    </div>
</body>
</html>
"""

        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = SMTP_USER or f"security-agent@{hostname}"
            msg["To"] = ADMIN_EMAIL

            msg.attach(MIMEText(text_body, "plain"))
            msg.attach(MIMEText(html_body, "html"))

            with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10) as server:
                server.starttls()
                if SMTP_USER and SMTP_PASS:
                    server.login(SMTP_USER, SMTP_PASS)
                server.send_message(msg)

            logger.info(f"Email alert successfully sent to {ADMIN_EMAIL} for [{risk}] {prediction}")
            return True
        except Exception as e:
            logger.error(f"Failed to send email alert to {ADMIN_EMAIL}: {e}")
            return False

# Global instance
email_service = EmailService()
