"""
email_service.py
================
Automated email notification service with anti-spam deduplication logic.
Sends structured HTML incident reports for HIGH or CRITICAL security risks.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta
from typing import Dict, Tuple
import app.config as config
from app.utils import get_recommendation
from app.logger import logger

class EmailService:
    """Manages security alert email generation, SMTP transport, and spam suppression."""

    def __init__(self):
        # Deduplication cache: key = (prediction, source_log), value = last_sent_datetime
        self._dedup_cache: Dict[Tuple[str, str], datetime] = {}

    def _should_suppress(self, prediction: str, source_log: str) -> bool:
        """Check if an alert for the same attack type and log source was sent recently."""
        key = (prediction, source_log)
        now = datetime.now()
        dedup_window = timedelta(minutes=config.ALERT_DEDUPLICATION_WINDOW_MINUTES)
        
        if key in self._dedup_cache:
            last_sent = self._dedup_cache[key]
            if now - last_sent < dedup_window:
                logger.info(
                    f"Email alert suppressed (anti-spam dedup window active for {prediction} on {source_log})"
                )
                return True

        self._dedup_cache[key] = now
        return False

    def send_alert(
        self,
        hostname: str,
        timestamp: str,
        prediction: str,
        confidence: float,
        risk: str,
        source_log: str,
        raw_log: str
    ) -> bool:
        """Send automated email alert for HIGH or CRITICAL security incidents."""
        
        # Read active configuration dynamically
        enabled = config.EMAIL_ENABLED or bool(config.SMTP_HOST and config.ADMIN_EMAIL)
        if not enabled:
            logger.debug("Email alert skipped: Email service is disabled or unconfigured.")
            return False

        # Filter only dangerous risks (HIGH or CRITICAL)
        if risk not in ("HIGH", "CRITICAL"):
            return False

        # Anti-Spam check
        if self._should_suppress(prediction, source_log):
            return False

        recommendation = get_recommendation(prediction)
        subject = f"🚨 [{risk} ALERT] VPS Security Threat Detected: {prediction} on {hostname}"
        admin_recipient = config.ADMIN_EMAIL or "aymaneelfounti@gmail.com"
        smtp_user = config.SMTP_USER or admin_recipient
        smtp_host = config.SMTP_HOST or "smtp.gmail.com"
        smtp_port = config.SMTP_PORT or 587
        smtp_pass = config.SMTP_PASS or ""

        # Short Threat Summary Explanation
        threat_summary = f"The AI Security Agent detected a high-risk security payload matching '{prediction}' in the log '{source_log}'. The AI model classified this event with {confidence * 100:.2f}% confidence."

        # Plain Text Body
        text_body = f"""
======================================================================
🛡️ ENTERPRISE VPS SECURITY AI — SHORT INCIDENT REPORT
======================================================================

[INCIDENT SUMMARY]
Server Hostname : {hostname}
Timestamp       : {timestamp}
Attack Category : {prediction}
AI Confidence   : {confidence * 100:.2f}%
Risk Level      : {risk}
Log Source      : {source_log}

[THREAT DESCRIPTION]
{threat_summary}

[INTERCEPTED RAW LOG]
{raw_log}

[RECOMMENDED ACTION]
{recommendation}

======================================================================
Automated alert generated by AI Security Agent for VPS.
"""

        # HTML Body - Styled Short Incident Report
        html_body = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f6f9; color: #212529; margin: 0; padding: 20px; }}
        .card {{ background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.12); max-width: 650px; margin: 0 auto; overflow: hidden; border: 1px solid #e9ecef; }}
        .header-critical {{ background: linear-gradient(135deg, #dc3545, #b02a37); color: #ffffff; padding: 20px 25px; text-align: left; }}
        .header-high {{ background: linear-gradient(135deg, #fd7e14, #d9480f); color: #ffffff; padding: 20px 25px; text-align: left; }}
        .header-title {{ margin: 0; font-size: 20px; font-weight: 700; }}
        .header-sub {{ margin: 5px 0 0 0; font-size: 13px; opacity: 0.9; }}
        .content {{ padding: 25px; }}
        .section-title {{ font-size: 14px; font-weight: 700; text-transform: uppercase; color: #6c757d; margin-bottom: 12px; border-bottom: 2px solid #e9ecef; padding-bottom: 5px; }}
        .grid {{ display: table; width: 100%; margin-bottom: 15px; }}
        .row {{ display: table-row; }}
        .cell-label {{ display: table-cell; font-weight: 600; color: #495057; padding: 6px 10px 6px 0; width: 140px; font-size: 13px; }}
        .cell-value {{ display: table-cell; color: #212529; padding: 6px 0; font-size: 13px; }}
        .badge {{ display: inline-block; padding: 4px 10px; border-radius: 4px; font-weight: 700; font-size: 12px; color: #ffffff; text-transform: uppercase; }}
        .badge-critical {{ background-color: #dc3545; }}
        .badge-high {{ background-color: #fd7e14; }}
        .raw-box {{ background-color: #1e1e1e; color: #00ff66; font-family: 'Consolas', 'Courier New', monospace; padding: 14px; border-radius: 6px; font-size: 12px; white-space: pre-wrap; word-break: break-all; margin: 10px 0 20px 0; border-left: 4px solid #00ff66; }}
        .recom-box {{ background-color: #e7f5ff; border-left: 4px solid #1c7ed6; padding: 15px; border-radius: 4px; font-size: 13px; line-height: 1.5; color: #1864ab; }}
        .footer {{ background-color: #f8f9fa; text-align: center; padding: 15px; font-size: 12px; color: #868e96; border-top: 1fr solid #dee2e6; }}
    </style>
</head>
<body>
    <div class="card">
        <div class="{ 'header-critical' if risk == 'CRITICAL' else 'header-high' }">
            <h2 class="header-title">🚨 [{risk}] Threat Alert: {prediction}</h2>
            <p class="header-sub">Enterprise VPS Security Agent &bull; Server: {hostname}</p>
        </div>
        <div class="content">
            <div class="section-title">📌 Incident Summary</div>
            <div class="grid">
                <div class="row"><div class="cell-label">Server Hostname:</div><div class="cell-value">{hostname}</div></div>
                <div class="row"><div class="cell-label">Timestamp:</div><div class="cell-value">{timestamp}</div></div>
                <div class="row"><div class="cell-label">Attack Category:</div><div class="cell-value"><strong>{prediction}</strong></div></div>
                <div class="row"><div class="cell-label">AI Confidence:</div><div class="cell-value"><strong>{confidence * 100:.2f}%</strong></div></div>
                <div class="row"><div class="cell-label">Risk Severity:</div><div class="cell-value"><span class="badge { 'badge-critical' if risk == 'CRITICAL' else 'badge-high' }">{risk}</span></div></div>
                <div class="row"><div class="cell-label">Source Log:</div><div class="cell-value"><code>{source_log}</code></div></div>
            </div>

            <div class="section-title">📜 Intercepted Log Snippet</div>
            <div class="raw-box">{raw_log}</div>

            <div class="section-title">💡 Actionable Remediation Steps</div>
            <div class="recom-box">
                <strong>Recommended Action:</strong><br>
                {recommendation}
            </div>
        </div>
        <div class="footer">
            Automated Incident Report &bull; Enterprise VPS Security AI System
        </div>
    </div>
</body>
</html>
"""

        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = smtp_user
            msg["To"] = admin_recipient

            msg.attach(MIMEText(text_body, "plain"))
            msg.attach(MIMEText(html_body, "html"))

            with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
                server.starttls()
                if smtp_user and smtp_pass:
                    server.login(smtp_user, smtp_pass)
                server.send_message(msg)

            logger.info(f"Email report successfully sent to {admin_recipient} for [{risk}] {prediction}")
            return True
        except Exception as e:
            logger.error(f"Failed to send email report to {admin_recipient}: {e}")
            return False

# Global instance
email_service = EmailService()
